### ISSUE TITLE
Performance in CLI vs Service vs Docker 2x, 4x reduction

### ISSUE THREAD

**Issue by fgonza2** [robmarkcole/tensorflow-lite-rest-server#42]
I am getting <200ms while i run it in CLI.  If i run it as a service it goes up to 500ms. then in docker goes up to 800ms

Running Ubuntu on a 7th Gen Intel CPU with Coral USB installed

Any ideas why?

**Comment by robmarkcole** [comment]
That is uesful to know, but your guesses are as good as mine
